language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install:
- pip install -r requirements.txt
- pip install coveralls
- pip install coverage

# command to run tests
script: nosetests

after_success:
  - coveralls
